#!/bin/bash

# Update system packages
sudo yum update -y

sudo wget -O /etc/yum.repos.d/jenkins.repo  https://pkg.jenkins.io/redhat-stable/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

# Install Java (Jenkins requires Java)
sudo yum install java-21-amazon-corretto -y


# Install Jenkins
sudo yum install jenkins -y

# Start Jenkins service
sudo systemctl start jenkins
sudo systemctl enable jenkins

# Print Jenkins initial admin password
echo "Jenkins Installation Complete!"
echo "To unlock Jenkins, use the following admin password:"
sudo cat /var/lib/jenkins/secrets/initialAdminPassword
